version: '3.1'

networks:
  fritzy-network:
    name: fritzy-network
    driver: bridge

services:
  fritzy-mongo:
    image: mongo:4.4.6 # use older version because 5.0+ requires CPU to have AVX support
    networks:
      - fritzy-network
    env_file:
      - '.env'
    container_name: fritzy-mongo
    command: ["--quiet", "--logpath", "/var/log/mongodb/fritzy-mongo.log"]

  fritzy-script:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    networks:
      - fritzy-network
    depends_on:
      - fritzy-mongo
    container_name: fritzy-script